//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkitSinghAssignments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentNewTable
    {
        public int Dept_Id { get; set; }
        public string Dept_Name { get; set; }
        public string Dept_Details { get; set; }
        public Nullable<int> TotalEmployee { get; set; }
        public string Location { get; set; }
    }
}
