
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AnkitSinghAssignments.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GuestList
{

    public int GuestId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public decimal Phone { get; set; }

    public bool WillAttend { get; set; }

}

}
