
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkitSinghAssignments.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class GuestList
    {

        public int GuestId { get; set; }

        [StringLength(50, MinimumLength = 5)]
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Common.RemoteClientServer.RemoteClientServer("IsEmailAvailable", "Assignment11",
        ErrorMessage = "Email already in use")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Phone is required")]
        public decimal Phone { get; set; }

        [Required(ErrorMessage = " WillAttend is required")]
        public bool WillAttend { get; set; }

    }

}
