

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AnkitSinghAssignments.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class GuestManagementEntities : DbContext
{
    public GuestManagementEntities()
        : base("name=GuestManagementEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<GuestList> GuestLists { get; set; }

    public virtual DbSet<UserComment> UserComments { get; set; }

}

}

