
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AnkitSinghAssignments.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserComment
    {

        public int Id { get; set; }

        [Required(ErrorMessage = "Name cannot be empty")]
        [RegularExpression("^([a-zA-Z]{2,})$", ErrorMessage = "Name contains only alphabets")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Comment cannot be empty")]
        public string Comments { get; set; }

    }

}
